Update basic.pane.c
mariotaku/moonlight-tv pull request #482
Opened 2024-12-01 08:57 UTC by vrokolos

Added 40,45,50,55 fps option

2024-12-01 15:54 UTC, mariotaku requested changes

2024-12-01 15:54 UTC, mariotaku commented on src/app/ui/settings/panes/basic.pane.c
> +        {"30 FPS",  40},
The labels needs to be updated too

2024-12-02 07:53 UTC, vrokolos commented
Oops... Corrected

2024-12-02 08:32 UTC, mariotaku approved these changes

2024-12-02 08:32 UTC, merged